
//브랜드
export const FETCH_BRAND_LIST='FETCH_BRAND_LIST'
export const FETCH_BRAND_DETAIL='FETCH_BRAND_DETAIL'

//상품
export const FETCH_CLOTH_LIST ='FETCH_CLOTH_LIST'
export const FETCH_CLOTH_DETAIL='FETCH_CLOTH_DETAIL'

//메인
export const FETCH_MAIN_BOTTOM='FETCH_MAIN_BOTTOM'
export const FETCH_MAIN_MIDDLE='FETCH_MAIN_MIDDLE'
//멤버

//댓글
export const FETCH_REPLY_NORMAL_LIST='FETCH_REPLY_NORMAL_LIST'
export const FETCH_REPLY_INSERT='FETCH_REPLY_INSERT'

export const FETCH_REPLY_DELETE='FETCH_REPLY_DELETE'

export const FETCH_REPLY_UPDATE='FETCH_REPLY_UPDATE'

//게시판

// Board
export const BOARD_LIST='BOARD_LIST'
export const BOARD_INSERT='BOARD_INSERT'
export const BOARD_DETAIL='BOARD_DETAIL'
export const BOARD_UPDATE='BOARD_UPDATE'
export const BOARD_UPDATE_DATA='BOARD_UPDATE_DATA'
export const BOARD_DELETE='BOARD_DELETE'


